### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by Ectalite** [arnbod/latex-to-text#2]
Hello,

Thanks for creating this project, I saw that you didn't add a license to it and because of this under [GitHub rules](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license) it means this project is closed source.
Could you please add a license to the project ?

**Comment by arnbod** [comment]
Done!

**Comment by Ectalite** [comment]
Thanks !
